# ============================================================
# 1. PCA FROM SCRATCH (no sklearn)
#    Understand what's actually happening under the hood
#
#   CODE GENERATED BY CLAUDE AI
# ============================================================

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

# --- generate correlated 2D data ---
# think of it like: one hidden variable 't' drives both features
# (e.g. 't' = overall body size, feature1 = height, feature2 = weight)
n = 200
t = np.random.randn(n)
X_raw = np.column_stack([
    t + np.random.randn(n) * 0.3,        # feature 1
    t * 0.8 + np.random.randn(n) * 0.4,  # feature 2, correlated with feature 1
])

# --- step 1: center the data ---
# subtract the mean of each feature so the cloud is centered at (0, 0)
# PCA measures variance, and variance is relative to the mean
X = X_raw - X_raw.mean(axis=0)

print("Mean before centering:", X_raw.mean(axis=0).round(3))
print("Mean after centering: ", X.mean(axis=0).round(3))  # should be ~[0, 0]

# --- step 2: covariance matrix ---
# C[i][j] = how much feature i and feature j vary together
# diagonal entries = variance of each feature
# off-diagonal = covariance between features (positive = move together)
C = (X.T @ X) / (n - 1)

print("\nCovariance matrix:")
print(C.round(4))
print("  top-left  = variance of feature 1:", round(C[0, 0], 4))
print("  bottom-right = variance of feature 2:", round(C[1, 1], 4))
print("  off-diagonal = covariance (correlation):", round(C[0, 1], 4))

# --- step 3: eigendecomposition ---
# this finds the directions (eigenvectors) and their importance (eigenvalues)
# eigenvalue = how much variance exists along that eigenvector direction
eigenvalues, eigenvectors = np.linalg.eigh(C)

# eigh returns smallest-first, so we reverse
idx = np.argsort(eigenvalues)[::-1]
eigenvalues  = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]  # each COLUMN is a principal component direction

print("\nEigenvalues:", eigenvalues.round(4))
print("  these are the variance along each PC")
print(f"  PC1 accounts for {eigenvalues[0] / eigenvalues.sum():.1%} of total variance")
print(f"  PC2 accounts for {eigenvalues[1] / eigenvalues.sum():.1%} of total variance")

print("\nEigenvectors (columns = PC directions):")
print(eigenvectors.round(4))
print("  PC1 direction:", eigenvectors[:, 0].round(4))
print("  PC2 direction:", eigenvectors[:, 1].round(4))
print("  note: PC2 is perpendicular to PC1 (dot product ≈ 0):",
      round(eigenvectors[:, 0] @ eigenvectors[:, 1], 10))

# --- step 4: project the data ---
# multiply each data point by the eigenvectors to get its PC coordinates
# X_pca[:, 0] = position of each point along PC1
# X_pca[:, 1] = position of each point along PC2
X_pca = X @ eigenvectors  # shape: (200, 2)

print("\nOriginal data shape:", X.shape)
print("Projected data shape:", X_pca.shape)
print("\nFirst 3 points in original space:", X[:3].round(3))
print("First 3 points in PC space:      ", X_pca[:3].round(3))

# --- step 5: reconstruct from k=1 component only ---
# project onto PC1, then project back into original space
# this shows you what information is kept vs. lost
X_1d    = X @ eigenvectors[:, [0]]           # (200, 1) — coordinates along PC1
X_recon = X_1d @ eigenvectors[:, [0]].T      # (200, 2) — back in original 2D space

recon_error = np.mean((X - X_recon) ** 2)
print(f"\nReconstruction MSE using only PC1: {recon_error:.4f}")
print("(lower = less information lost)")

# --- plot ---
fig, axes = plt.subplots(1, 3, figsize=(14, 4))

# plot 1: original data with PC axes drawn on top
axes[0].scatter(X[:, 0], X[:, 1], alpha=0.4, s=20, color='steelblue')
for i, (color, label) in enumerate(zip(['tomato', 'seagreen'], ['PC1', 'PC2'])):
    # scale the arrow length by sqrt(eigenvalue) so it reflects actual spread
    v = eigenvectors[:, i] * np.sqrt(eigenvalues[i]) * 2
    axes[0].annotate('', xy=v, xytext=-v,
                     arrowprops=dict(arrowstyle='<->', color=color, lw=2.5))
    axes[0].text(v[0] * 1.15, v[1] * 1.15, label, color=color,
                 fontweight='bold', fontsize=11)
axes[0].set_title('Original data + PC directions')
axes[0].set_aspect('equal')
axes[0].axhline(0, color='grey', lw=0.5)
axes[0].axvline(0, color='grey', lw=0.5)
axes[0].set_xlabel('feature 1')
axes[0].set_ylabel('feature 2')

# plot 2: same data, now viewed in PC coordinate system
# notice PC1 is now the horizontal axis, and the cloud is "aligned"
axes[1].scatter(X_pca[:, 0], X_pca[:, 1], alpha=0.4, s=20, color='steelblue')
axes[1].set_xlabel('PC1 (most variance)')
axes[1].set_ylabel('PC2 (remaining variance)')
axes[1].set_title('Data in PC space\n(PCA just rotated the axes)')
axes[1].set_aspect('equal')
axes[1].axhline(0, color='grey', lw=0.5)
axes[1].axvline(0, color='grey', lw=0.5)

# plot 3: original vs reconstruction from 1 PC
# grey lines connect each point to where it lands on PC1 — that gap is lost info
axes[2].scatter(X[:, 0], X[:, 1], alpha=0.25, s=20,
                color='steelblue', label='original')
axes[2].scatter(X_recon[:, 0], X_recon[:, 1], alpha=0.7, s=20,
                color='tomato', label='reconstructed (PC1 only)')
for i in range(0, n, 8):
    axes[2].plot([X[i, 0], X_recon[i, 0]],
                 [X[i, 1], X_recon[i, 1]], 'grey', lw=0.6, alpha=0.5)
axes[2].set_title('Reconstruction from PC1 only\ngrey lines = information lost')
axes[2].set_aspect('equal')
axes[2].legend(fontsize=8)
axes[2].set_xlabel('feature 1')
axes[2].set_ylabel('feature 2')

plt.suptitle('PCA from scratch — step by step', fontsize=13, y=1.02)
plt.tight_layout()
plt.savefig('pca_scratch.png', dpi=150, bbox_inches='tight')
plt.show()
print("\nSaved pca_scratch.png")
